services:
  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    image: local/server:dev
    environment:
      NODE_ENV: production
    env_file:
      - ./apps/server/.env.prod
    ports:
      - "3000:3000"
    networks:
      - appnet

networks:
  appnet:
